help:
	@echo "Make Commands:"
	@echo "build-dev (Builds Vue App using development mode)"
	@echo "build-prod (Builds Vue App using production mode)"
	@echo "run-local (Runs Vue App locally using development mode)"

build-dev:
	npm run build-dev

build-prod:
	npm run build

run-local:
	npm run serve