export const releases = [
    {
        "url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/36072029",
        "assets_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/36072029/assets",
        "upload_url": "https://uploads.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/36072029/assets{?name,label}",
        "html_url": "https://github.com/marqaaron/spinnaker-advanced-user-lab/releases/tag/v1.2.3",
        "id": 36072029,
        "author": {
            "login": "marqaaron",
            "id": 57965459,
            "node_id": "MDQ6VXNlcjU3OTY1NDU5",
            "avatar_url": "https://avatars2.githubusercontent.com/u/57965459?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marqaaron",
            "html_url": "https://github.com/marqaaron",
            "followers_url": "https://api.github.com/users/marqaaron/followers",
            "following_url": "https://api.github.com/users/marqaaron/following{/other_user}",
            "gists_url": "https://api.github.com/users/marqaaron/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marqaaron/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marqaaron/subscriptions",
            "organizations_url": "https://api.github.com/users/marqaaron/orgs",
            "repos_url": "https://api.github.com/users/marqaaron/repos",
            "events_url": "https://api.github.com/users/marqaaron/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marqaaron/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTM2MDcyMDI5",
        "tag_name": "v1.2.3",
        "target_commitish": "main",
        "name": "v1.2.3",
        "draft": false,
        "prerelease": false,
        "created_at": "2021-01-07T00:23:06Z",
        "published_at": "2021-01-07T00:24:49Z",
        "assets": [

        ],
        "tarball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/tarball/v1.2.3",
        "zipball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/zipball/v1.2.3",
        "body": "### New Features & Major Changes\r\n* None\r\n\r\n### Fixes\r\n* Change to Vue Webpack config to fix production build issues.\r\n* Disable Image Requests in Releases pending future fix.\r\n\r\n### Minor Changes\r\n* None"
    },
    {
        "url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/36008827",
        "assets_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/36008827/assets",
        "upload_url": "https://uploads.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/36008827/assets{?name,label}",
        "html_url": "https://github.com/marqaaron/spinnaker-advanced-user-lab/releases/tag/v1.2.2",
        "id": 36008827,
        "author": {
            "login": "marqaaron",
            "id": 57965459,
            "node_id": "MDQ6VXNlcjU3OTY1NDU5",
            "avatar_url": "https://avatars2.githubusercontent.com/u/57965459?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marqaaron",
            "html_url": "https://github.com/marqaaron",
            "followers_url": "https://api.github.com/users/marqaaron/followers",
            "following_url": "https://api.github.com/users/marqaaron/following{/other_user}",
            "gists_url": "https://api.github.com/users/marqaaron/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marqaaron/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marqaaron/subscriptions",
            "organizations_url": "https://api.github.com/users/marqaaron/orgs",
            "repos_url": "https://api.github.com/users/marqaaron/repos",
            "events_url": "https://api.github.com/users/marqaaron/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marqaaron/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTM2MDA4ODI3",
        "tag_name": "v1.2.2",
        "target_commitish": "main",
        "name": "v1.2.2",
        "draft": false,
        "prerelease": false,
        "created_at": "2021-01-05T17:46:01Z",
        "published_at": "2021-01-05T17:48:47Z",
        "assets": [

        ],
        "tarball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/tarball/v1.2.2",
        "zipball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/zipball/v1.2.2",
        "body": "### New Features & Major Changes\r\n* Enhancement to SAUL Releases Content\r\n    * Inject Docker Image information into the List of Releases\r\n\r\n### Fixes\r\n* None\r\n\r\n### Minor Changes\r\n* None"
    },
    {
        "url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35960392",
        "assets_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35960392/assets",
        "upload_url": "https://uploads.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35960392/assets{?name,label}",
        "html_url": "https://github.com/marqaaron/spinnaker-advanced-user-lab/releases/tag/v1.2.1",
        "id": 35960392,
        "author": {
            "login": "marqaaron",
            "id": 57965459,
            "node_id": "MDQ6VXNlcjU3OTY1NDU5",
            "avatar_url": "https://avatars2.githubusercontent.com/u/57965459?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marqaaron",
            "html_url": "https://github.com/marqaaron",
            "followers_url": "https://api.github.com/users/marqaaron/followers",
            "following_url": "https://api.github.com/users/marqaaron/following{/other_user}",
            "gists_url": "https://api.github.com/users/marqaaron/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marqaaron/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marqaaron/subscriptions",
            "organizations_url": "https://api.github.com/users/marqaaron/orgs",
            "repos_url": "https://api.github.com/users/marqaaron/repos",
            "events_url": "https://api.github.com/users/marqaaron/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marqaaron/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTM1OTYwMzky",
        "tag_name": "v1.2.1",
        "target_commitish": "main",
        "name": "v1.2.1",
        "draft": false,
        "prerelease": false,
        "created_at": "2021-01-04T19:52:17Z",
        "published_at": "2021-01-04T19:52:47Z",
        "assets": [

        ],
        "tarball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/tarball/v1.2.1",
        "zipball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/zipball/v1.2.1",
        "body": "### New Features & Major Changes\r\n* None\r\n\r\n### Fixes\r\n1. Typo fix in Debug Admin Guide\r\n2. Update moment.js npm package\r\n3. Add debug logging to requestApplications request\r\n4. Correct regression in Logout button functionality injected by 1.2.0\r\n\r\n### Minor Changes\r\n1. Change to Invalid Session User Experience\r\n    * Users now given the option to log out from UI alert rather than being told to logout using the logout button.\r\n2. Hide Documentation Icon on Navbar when user not logged in.\r\n"
    },
    {
        "url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35912321",
        "assets_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35912321/assets",
        "upload_url": "https://uploads.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35912321/assets{?name,label}",
        "html_url": "https://github.com/marqaaron/spinnaker-advanced-user-lab/releases/tag/v1.2.0",
        "id": 35912321,
        "author": {
            "login": "marqaaron",
            "id": 57965459,
            "node_id": "MDQ6VXNlcjU3OTY1NDU5",
            "avatar_url": "https://avatars2.githubusercontent.com/u/57965459?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marqaaron",
            "html_url": "https://github.com/marqaaron",
            "followers_url": "https://api.github.com/users/marqaaron/followers",
            "following_url": "https://api.github.com/users/marqaaron/following{/other_user}",
            "gists_url": "https://api.github.com/users/marqaaron/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marqaaron/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marqaaron/subscriptions",
            "organizations_url": "https://api.github.com/users/marqaaron/orgs",
            "repos_url": "https://api.github.com/users/marqaaron/repos",
            "events_url": "https://api.github.com/users/marqaaron/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marqaaron/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTM1OTEyMzIx",
        "tag_name": "v1.2.0",
        "target_commitish": "main",
        "name": "v1.2.0",
        "draft": false,
        "prerelease": false,
        "created_at": "2021-01-03T20:14:49Z",
        "published_at": "2021-01-03T20:15:45Z",
        "assets": [

        ],
        "tarball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/tarball/v1.2.0",
        "zipball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/zipball/v1.2.0",
        "body": "### New Features & Major Changes\r\n1. Modify Environment Variable Approach to improve Docker Build Process\r\n    * Further reduces Docker image size by 64%; an overall 76% reduction from the v1.0.1 release.\r\n2. Create Admin View with SAUL Releases module\r\n    * Retrieves release list from Github and displays in-app (if access to Github available)\r\n    * Provides indication of currently deployed release (if release list successfully retrieved)\r\n    * Provides indication of upgrade available (if release list successfully retrieved)\r\n3. Implement Configurable RBAC at the 'View' Level of the Application\r\n    * Restricted Access may be applied to the Admin View\r\n    * Set RBAC_ROLE_ADMIN_VIEW in your ConfigMap to the desired Spinnaker User Group role that should have access\r\n        * See In App Docs for more information\r\n4. Implement Configurable Debug Mode in Production Builds\r\n    * Set DEBUG_MODE in your ConfigMap\r\n        * See In App Docs for more information\r\n\r\n### Fixes\r\n1. Improve API request error handling in Pipeline Expression Test Environment\r\n\r\n### Minor Changes\r\n1. Upgrade all npm module dependencies to latest stable versions\r\n2. Improved console.log messages in development environment\r\n3. Refactor Pipeline Expression Test Environment Test History into multiple components"
    },
    {
        "url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35887366",
        "assets_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35887366/assets",
        "upload_url": "https://uploads.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35887366/assets{?name,label}",
        "html_url": "https://github.com/marqaaron/spinnaker-advanced-user-lab/releases/tag/v1.1.0",
        "id": 35887366,
        "author": {
            "login": "marqaaron",
            "id": 57965459,
            "node_id": "MDQ6VXNlcjU3OTY1NDU5",
            "avatar_url": "https://avatars2.githubusercontent.com/u/57965459?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marqaaron",
            "html_url": "https://github.com/marqaaron",
            "followers_url": "https://api.github.com/users/marqaaron/followers",
            "following_url": "https://api.github.com/users/marqaaron/following{/other_user}",
            "gists_url": "https://api.github.com/users/marqaaron/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marqaaron/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marqaaron/subscriptions",
            "organizations_url": "https://api.github.com/users/marqaaron/orgs",
            "repos_url": "https://api.github.com/users/marqaaron/repos",
            "events_url": "https://api.github.com/users/marqaaron/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marqaaron/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTM1ODg3MzY2",
        "tag_name": "v1.1.0",
        "target_commitish": "main",
        "name": "v1.1.0",
        "draft": false,
        "prerelease": false,
        "created_at": "2020-12-31T23:59:43Z",
        "published_at": "2021-01-01T00:18:40Z",
        "assets": [

        ],
        "tarball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/tarball/v1.1.0",
        "zipball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/zipball/v1.1.0",
        "body": "### New Features & Major Changes\r\n1. In-App Documentation & Help Guides Framework\r\n    * Viewable anywhere in the Application via Slider Sidebar\r\n    * Viewable as a standalone View within the App\r\n2. Pipeline Expression Test Environment (PETE) Documentation\r\n    * All six features of PETE fully documented\r\n2. Improved Docker Build Process to reduce Image Size\r\n    * Implements Docker multi-stage build process reducing image size by 35%\r\n\r\n### Fixes\r\n1. Inject correct commit short hash into Builds and apply to Docker Images.\r\n\r\n### Minor Changes\r\n1. Add CONTRIBUTING.md file to repository\r\n2. Changes to In-App Main Menu architecture to support new \"Views\" approach to serving \"modules\""
    },
    {
        "url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35738400",
        "assets_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35738400/assets",
        "upload_url": "https://uploads.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35738400/assets{?name,label}",
        "html_url": "https://github.com/marqaaron/spinnaker-advanced-user-lab/releases/tag/v1.0.1",
        "id": 35738400,
        "author": {
            "login": "marqaaron",
            "id": 57965459,
            "node_id": "MDQ6VXNlcjU3OTY1NDU5",
            "avatar_url": "https://avatars2.githubusercontent.com/u/57965459?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marqaaron",
            "html_url": "https://github.com/marqaaron",
            "followers_url": "https://api.github.com/users/marqaaron/followers",
            "following_url": "https://api.github.com/users/marqaaron/following{/other_user}",
            "gists_url": "https://api.github.com/users/marqaaron/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marqaaron/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marqaaron/subscriptions",
            "organizations_url": "https://api.github.com/users/marqaaron/orgs",
            "repos_url": "https://api.github.com/users/marqaaron/repos",
            "events_url": "https://api.github.com/users/marqaaron/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marqaaron/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTM1NzM4NDAw",
        "tag_name": "v1.0.1",
        "target_commitish": "main",
        "name": "v1.0.1",
        "draft": false,
        "prerelease": false,
        "created_at": "2020-12-26T18:58:43Z",
        "published_at": "2020-12-26T19:00:30Z",
        "assets": [

        ],
        "tarball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/tarball/v1.0.1",
        "zipball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/zipball/v1.0.1",
        "body": "## DEPRECATED"
    },
    {
        "url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35720347",
        "assets_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35720347/assets",
        "upload_url": "https://uploads.github.com/repos/marqaaron/spinnaker-advanced-user-lab/releases/35720347/assets{?name,label}",
        "html_url": "https://github.com/marqaaron/spinnaker-advanced-user-lab/releases/tag/v1.0.0",
        "id": 35720347,
        "author": {
            "login": "marqaaron",
            "id": 57965459,
            "node_id": "MDQ6VXNlcjU3OTY1NDU5",
            "avatar_url": "https://avatars2.githubusercontent.com/u/57965459?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marqaaron",
            "html_url": "https://github.com/marqaaron",
            "followers_url": "https://api.github.com/users/marqaaron/followers",
            "following_url": "https://api.github.com/users/marqaaron/following{/other_user}",
            "gists_url": "https://api.github.com/users/marqaaron/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marqaaron/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marqaaron/subscriptions",
            "organizations_url": "https://api.github.com/users/marqaaron/orgs",
            "repos_url": "https://api.github.com/users/marqaaron/repos",
            "events_url": "https://api.github.com/users/marqaaron/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marqaaron/received_events",
            "type": "User",
            "site_admin": false
        },
        "node_id": "MDc6UmVsZWFzZTM1NzIwMzQ3",
        "tag_name": "v1.0.0",
        "target_commitish": "main",
        "name": "v1.0.0",
        "draft": false,
        "prerelease": false,
        "created_at": "2020-12-25T16:10:55Z",
        "published_at": "2020-12-25T16:16:32Z",
        "assets": [

        ],
        "tarball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/tarball/v1.0.0",
        "zipball_url": "https://api.github.com/repos/marqaaron/spinnaker-advanced-user-lab/zipball/v1.0.0",
        "body": "## DEPRECATED"
    }
];

export const images = [
    {
        "creator": 9784516,
        "id": 131371727,
        "image_id": null,
        "images": [
            {
                "architecture": "amd64",
                "features": "",
                "variant": null,
                "digest": "sha256:f62296842bc6478478ec5af119e2116fe00b56e276313c4356482767943975e7",
                "os": "linux",
                "os_features": "",
                "os_version": null,
                "size": 27442245,
                "status": "active",
                "last_pulled": "2021-01-04T20:58:19.709308Z",
                "last_pushed": "2021-01-04T19:55:18.440537Z"
            }
        ],
        "last_updated": "2021-01-04T19:55:18.440537Z",
        "last_updater": 9784516,
        "last_updater_username": "marqaaron",
        "name": "latest",
        "repository": 10517719,
        "full_size": 27442245,
        "v2": true,
        "tag_status": "active",
        "tag_last_pulled": "2021-01-04T20:58:19.709308Z",
        "tag_last_pushed": "2021-01-04T19:55:18.440537Z"
    },
    {
        "creator": 9784516,
        "id": 131961678,
        "image_id": null,
        "images": [
            {
                "architecture": "amd64",
                "features": "",
                "variant": null,
                "digest": "sha256:f62296842bc6478478ec5af119e2116fe00b56e276313c4356482767943975e7",
                "os": "linux",
                "os_features": "",
                "os_version": null,
                "size": 27442245,
                "status": "active",
                "last_pulled": "2021-01-04T20:58:19.709308Z",
                "last_pushed": "2021-01-04T19:55:18.440537Z"
            }
        ],
        "last_updated": "2021-01-04T19:55:17.37199Z",
        "last_updater": 9784516,
        "last_updater_username": "marqaaron",
        "name": "1.2.1",
        "repository": 10517719,
        "full_size": 27442245,
        "v2": true,
        "tag_status": "active",
        "tag_last_pulled": "2021-01-04T20:58:19.709308Z",
        "tag_last_pushed": "2021-01-04T19:55:17.37199Z"
    },
    {
        "creator": 9784516,
        "id": 131855472,
        "image_id": null,
        "images": [
            {
                "architecture": "amd64",
                "features": "",
                "variant": null,
                "digest": "sha256:c89c27ab8d7f84f2ce96cfe5f37d604c51ae2e109796b369502b69f8e8e0e6aa",
                "os": "linux",
                "os_features": "",
                "os_version": null,
                "size": 27435032,
                "status": "active",
                "last_pulled": "2021-01-04T19:23:04.267978Z",
                "last_pushed": "2021-01-03T20:18:07.025142Z"
            }
        ],
        "last_updated": "2021-01-03T20:18:06.075181Z",
        "last_updater": 9784516,
        "last_updater_username": "marqaaron",
        "name": "1.2.0",
        "repository": 10517719,
        "full_size": 27435032,
        "v2": true,
        "tag_status": "active",
        "tag_last_pulled": "2021-01-04T19:23:04.267978Z",
        "tag_last_pushed": "2021-01-03T20:18:06.075181Z"
    },
    {
        "creator": 9784516,
        "id": 131764147,
        "image_id": null,
        "images": [
            {
                "architecture": "amd64",
                "features": "",
                "variant": null,
                "digest": "sha256:f67ce493ee144ade3504ed712f2e65cd4f4bb210035e7281389d1bec7953aafb",
                "os": "linux",
                "os_features": "",
                "os_version": null,
                "size": 75126051,
                "status": "active",
                "last_pulled": "2021-01-03T19:34:34.294385Z",
                "last_pushed": "2021-01-01T00:20:17.916375Z"
            }
        ],
        "last_updated": "2021-01-01T00:20:16.732299Z",
        "last_updater": 9784516,
        "last_updater_username": "marqaaron",
        "name": "1.1.0",
        "repository": 10517719,
        "full_size": 75126051,
        "v2": true,
        "tag_status": "active",
        "tag_last_pulled": "2021-01-03T19:34:34.294385Z",
        "tag_last_pushed": "2021-01-01T00:20:16.732299Z"
    },
    {
        "creator": 9784516,
        "id": 131397304,
        "image_id": null,
        "images": [
            {
                "architecture": "amd64",
                "features": "",
                "variant": null,
                "digest": "sha256:9d8e6e5ce361856506745c6c23a19bde467564eaef2f7db193bd557398f43898",
                "os": "linux",
                "os_features": "",
                "os_version": null,
                "size": 99110503,
                "status": "active",
                "last_pulled": "2021-01-01T00:19:36.275482Z",
                "last_pushed": "2020-12-26T19:02:00.857251Z"
            }
        ],
        "last_updated": "2020-12-26T19:01:59.198767Z",
        "last_updater": 9784516,
        "last_updater_username": "marqaaron",
        "name": "1.0.1",
        "repository": 10517719,
        "full_size": 99110503,
        "v2": true,
        "tag_status": "active",
        "tag_last_pulled": "2021-01-01T00:19:36.275482Z",
        "tag_last_pushed": "2020-12-26T19:01:59.198767Z"
    },
    {
        "creator": 9784516,
        "id": 131371726,
        "image_id": null,
        "images": [
            {
                "architecture": "amd64",
                "features": "",
                "variant": null,
                "digest": "sha256:e738844b835f383d8028d6cd052780ea90e8a2532ab36e93dfbc345def4d481d",
                "os": "linux",
                "os_features": "",
                "os_version": null,
                "size": 99116760,
                "status": "active",
                "last_pulled": "2020-12-31T17:18:30.612477Z",
                "last_pushed": "2020-12-25T16:18:07.307261Z"
            }
        ],
        "last_updated": "2020-12-25T16:18:06.048182Z",
        "last_updater": 9784516,
        "last_updater_username": "marqaaron",
        "name": "1.0.0",
        "repository": 10517719,
        "full_size": 99116760,
        "v2": true,
        "tag_status": "active",
        "tag_last_pulled": "2020-12-31T17:18:30.612477Z",
        "tag_last_pushed": "2020-12-25T16:18:06.048182Z"
    }
]